---
name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy rustfmt

      - name: Install the dependencies
        run: |
          sudo apt update && \
          sudo apt install -y \
            podman \
            qemu-user-static \
            binutils \
            binutils-aarch64-linux-gnu && \
          cargo binstall --no-confirm cross

      - name: Building for aarch64-unknown-linux-musl
        run: |
          CROSS_CONTAINER_ENGINE=podman cross build --target=aarch64-unknown-linux-musl --release
          cp target/aarch64-unknown-linux-musl/release/agadir agadir-linux-arm64
          aarch64-linux-gnu-strip agadir-linux-arm64

      - name: Building for x86_64-unknown-linux-musl
        run: |
          CROSS_CONTAINER_ENGINE=podman cross build --target=x86_64-unknown-linux-musl --release
          cp target/x86_64-unknown-linux-musl/release/agadir agadir-linux-x86_64
          strip agadir-linux-x86_64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            [Release.md](${{ github.server_url }}/${{ github.repository }}/blob/master/Release.md)
          files: "agadir*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
